# Generated by Django 5.1.1 on 2024-10-10 14:24

import aplic.models
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('valor_foto', models.FloatField(verbose_name='Valor Foto')),
                ('valor_hora', models.FloatField(verbose_name='Valor Hora')),
            ],
            options={
                'verbose_name': 'Categoria de evento',
                'verbose_name_plural': 'Categorias de evento',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Fotografo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], verbose_name='Sexo')),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=aplic.models.get_file_path, variations={'thumb': {'crop': True, 'height': 260, 'width': 420}}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Fotografo',
                'verbose_name_plural': 'Fotografos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, verbose_name='Data/Hora')),
                ('pacote_tipo', models.CharField(blank=True, choices=[('Quantidade de fotos', 'Quantidade de fotos'), ('Tempo de serviço', 'Tempo de serviço')], verbose_name='Pacote')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Categoria', to='aplic.categoriaevento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='aplic.cliente')),
                ('fotografos', models.ManyToManyField(to='aplic.fotografo')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, verbose_name='Data')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Evento', to='aplic.evento')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=aplic.models.get_file_path, variations={}, verbose_name='Foto')),
                ('entrega_tipo', models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Revelada 20x30', 'Revelada 20x30'), ('Revelada 30x40', 'Revelada 30x40'), ('Revelada 40x60', 'Revelada 40x60'), ('Revelada 60x90', 'Revelada 60x90')], verbose_name='Tipo de entrega')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entrega', to='aplic.entrega')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('tipo', models.CharField(blank=True, choices=[('Camera', 'Camera'), ('Lente', 'Lente'), ('Flash', 'Flash'), ('Iluminacao', 'Iluminação'), ('Memoria', 'Memória'), ('Outros', 'Outros')], verbose_name='Tipo')),
                ('estado', models.CharField(blank=True, choices=[('Funcional', 'Funcional'), ('Defeituoso', 'Defeituoso'), ('Em Conserto', 'Em Conserto')], verbose_name='Estado')),
                ('data_fabric', models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Fabricação')),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Equipamentos', to='aplic.fotografo')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('fotografos', models.ManyToManyField(to='aplic.fotografo')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
    ]
