# Generated by Django 5.1.1 on 2024-10-08 13:06

import aplic.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField(max_length=11, verbose_name='CPF')),
                ('telefone', models.IntegerField(max_length=15, verbose_name='Telefone')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sexo', models.CharField(max_length=20, verbose_name='Sexo')),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=aplic.models.get_file_path, variations={'thumb': {'crop': True, 'height': 260, 'width': 420}}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Fotografo',
                'verbose_name_plural': 'Fotografos',
            },
        ),
    ]
