# Generated by Django 5.1.1 on 2024-10-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='data',
            field=models.DateField(blank=True, verbose_name='Data da entrega'),
        ),
    ]
