# Generated by Django 5.1.1 on 2024-10-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografo',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF'),
        ),
    ]
