# Generated by Django 4.2.16 on 2024-11-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_alter_entrega_data_alter_evento_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fotografos',
            field=models.ManyToManyField(blank=True, null=True, to='aplic.fotografo'),
        ),
    ]
