# Generated by Django 5.1.1 on 2024-10-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_alter_fotografo_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografo',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='fotografo',
            name='telefone',
            field=models.CharField(max_length=14, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('tipo', models.CharField(blank=True, choices=[('Camera', 'Camera'), ('Lente', 'Lente'), ('Flash', 'Flash'), ('Iluminacao', 'Iluminação'), ('Memoria', 'Memória'), ('Outros', 'Outros')], verbose_name='Tipo')),
                ('estado', models.CharField(blank=True, choices=[('Funcional', 'Funcional'), ('Defeituoso', 'Defeituoso'), ('Em Conserto', 'Em Conserto')], verbose_name='Estado')),
                ('data_fabric', models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Fabricação')),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Equipamentos', to='aplic.fotografo')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
    ]
