# Generated by Django 4.2.16 on 2024-11-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_alter_evento_fotografos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
