# Generated by Django 4.2.16 on 2024-11-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fotografos',
            field=models.ManyToManyField(blank=True, to='aplic.fotografo'),
        ),
    ]
