# Generated by Django 5.1.1 on 2024-10-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
