# Generated by Django 5.1.1 on 2024-10-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_alter_departamento_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('valor_foto', models.FloatField(verbose_name='Valor Foto')),
                ('valor_hora', models.FloatField(verbose_name='Valor Hora')),
            ],
            options={
                'verbose_name': 'Categoria de evento',
                'verbose_name_plural': 'Categorias de evento',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, verbose_name='Data/Hora')),
                ('pacote', models.CharField(blank=True, choices=[('Quantidade de fotos', 'Quantidade de fotos'), ('Tempo de serviço', 'Tempo de serviço')], verbose_name='Pacote')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Categoria', to='aplic.categoriaevento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
