# Generated by Django 5.1.1 on 2024-10-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_evento_hora_alter_evento_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='hora',
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(blank=True, verbose_name='Data/Hora'),
        ),
    ]
