# Generated by Django 5.1.1 on 2024-10-10 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0009_remove_evento_hora_alter_evento_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='pacote',
            new_name='pacote_tipo',
        ),
        migrations.AddField(
            model_name='evento',
            name='fotografos',
            field=models.ManyToManyField(to='aplic.fotografo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='aplic.cliente'),
            preserve_default=False,
        ),
    ]
